openapi: 3.0.4
info:
  title: order-status-api-nano
  description: A service that returns the status of an order under fulfilment.
  termsOfService: https://ibm.com/terms/
  contact:
    name: Ricky Moorhouse
    url: www.ibm.com
    email: api-connect@ibm.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: '1'
externalDocs:
  description: Find out more about IBM DataPower Nano Gateway
  url: https://ibm.com
servers:
  - url: https://sample-api.us-east-a.apiconnect.automation.ibm.com/orders/order
tags:
  - name: order-status
    description: Everything about IBM DataPower Nano Gateway
    externalDocs:
      description: Find out more
      url: www.ibm.com
paths:
  /{orderNumber}:
    parameters:
      - name: orderNumber
        in: path
        description: >-
          Order number to lookup - you should find this in your confirmation
          e-mail
        required: true
        schema:
          type: string
    get:
      summary: Retrieve the details of your order.
      responses:
        '200':
          description: Order found successfully
          content:
            application/json:
              schema:
                title: Order Details
                type: object
                properties:
                  order_number:
                    title: Order Number
                    type: string
                    example: ORD00989792
                  tracking_status:
                    title: Tracking Status
                    type: object
                    properties: {}
                  shipped_at:
                    title: Date Shipped
                    type: string
                    format: date-time
                  created_at:
                    title: Date Order Created
                    type: string
                    format: date-time
                  status:
                    title: Order Status
                    type: string
                    enum:
                      - SHIPPED
                      - PICKED
                      - PENDING
                      - DELIVERED
                  tracking_reference:
                    title: Tracking Reference
                    type: string
