kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: policy-sequence
  namespace: orders-api
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: orders-api:extract-identity:1.0
    - $ref: orders-api:authenticate:1.0
    - $ref: orders-api:authorize:1.0
    - $ref: orders-api:invoke-order-system:1.0
    - $ref: orders-api:parse-order-details:1.0
    - $ref: orders-api:set-body:1.0
    - $ref: orders-api:invoke-tracking:1.0
    - $ref: orders-api:parse-tracking:1.0
    - $ref: orders-api:set-response:1.0

    
