swagger: '2.0'
info:
  title: Echo API
  x-ibm-name: echo-api
  version: 1.1.0
  description: Sample Echo API
  contact:
    name: Ricky Moorhouse
    email: moorh@uk.ibm.com
host: $(catalog.host)
schemes:
  - https
basePath: /public
produces:
  - application/json
security: []
parameters:
  text:
    name: text
    type: string
    required: false
    in: query
    description: Text passed in
definitions:
  responseObject:
    properties:
      text:
        type: string
paths:
  /echo:
    get:
      description: Get echo response
      operationId: getEcho
      tags:
        - echo
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/responseObject'
      parameters:
        - $ref: '#/parameters/text'
tags:
  - name: echo
    description: ''
    externalDocs:
      url: ''
      description: ''
